Feature/components
ensisf/junior-course-boilerplate pull request #3
Opened 2019-12-08 19:44 UTC by ensisf

2019-12-11 15:40 UTC, CSSSR-School requested changes

2019-12-11 15:40 UTC, CSSSR-School commented on src/components/grid/index.jsx
> +    <div className={`${styled.grid} ${className}`} style={style} {...attrs}>
Если это "Список товаров", то почему это `div`, а не `ul`?

2019-12-11 20:12 UTC, ensisf commented on src/components/grid/index.jsx
> +    <div className={`${styled.grid} ${className}`} style={style} {...attrs}>
Сначала я так и сделал - `ul->li->ProductCard`
Потом подумал, что интереснее вместо списка сделать "более" универсальный компонент `Grid`, который можно использовать не только как список продуктов, но и как сетку для чего угодно. Он будет рендерить потомков, и управлять их поведением через пропсы и `CSS grid`. Плюс рутовый тег компонента `ProductCard` - `div`, что значит его нельзя использовать как непосредственного потомка для `ul`(Вопрос: в Реакте есть возможность указывать, какой тег нужно отрендерить? Например `<Component is={'section'}`/>). 
Это позволило:
1) создать компонент "сетки", который можно переиспользовать, а не просто список продуктов,
2) избежать "избыточного" `li` (только в данной ситуации избыточного, в большинстве случаев я для списков, конечно, использую `ul->li`;

2019-12-12 06:59 UTC, CSSSR-School requested changes

2019-12-12 06:59 UTC, CSSSR-School commented on src/utils/constants/index.js
> +export const HEADINGS_MAP = {
В целом, раз уже это Map, то почему бы не заюзать Map из js?)

2019-12-12 07:01 UTC, CSSSR-School commented on src/components/grid/index.jsx
> +    <div className={`${styled.grid} ${className}`} style={style} {...attrs}>
Получается, что Grid не такой уж и универсальный, раз с его помощью нельзя отрендерить ul.

Тут дело не в переиспользуемости, а в семантике разметки. Очевидно, что список товаров это ul. Как ты будешь переключаться между карточками, например с клавиатуры? Если это будет ul, тогда браузер всё сделает за тебя. А если это будут просто div, то придётся заморичться.

Теги ты можешь прокидывать через пропсы, у тебя есть похожее решение через Tag и HEADINGS_MAP

2019-12-15 14:24 UTC, CSSSR-School approved these changes

2019-12-15 14:30 UTC, merged