Feature/controlled controls and optimization 1
ensisf/junior-course-boilerplate pull request #6
Opened 2020-01-05 19:09 UTC by ensisf

2020-01-07 08:06 UTC, vislogurov requested changes

2020-01-07 08:06 UTC, vislogurov commented on package.json
> +      "react-hooks"
Откуда это тут взялось? Тем более, что далее по коду нет хуков.

2020-01-07 09:20 UTC, ensisf commented on package.json
> +      "react-hooks"
С другого [ПР](https://github.com/ensisf/junior-course-boilerplate/pull/5) попало) Я пробовал переписать Арр на хуки.

2020-01-09 17:11 UTC, vislogurov approved these changes

2020-01-11 15:49 UTC, merged