Feature/redux
ensisf/junior-course-boilerplate pull request #9
Opened 2020-03-26 16:50 UTC by ensisf

2020-03-28 08:33 UTC, kuflash commented on src/redux/actions/helpers/index.js
> +export const getActiveCategiriesNames = categories =>
Не в качестве замечания - небольшая опечатка: `getActiveCategoriesNames`

2020-03-28 08:49 UTC, kuflash requested changes
Из критичных моментов только момент с первоначальными значениями фильтра. Почему-то при открытии страницы, `min` и `max` значения цены выставлены в 0. Хотя в одном из предыдущих этапов было условие, что по умолчанию они должны быть равны `min` и `max` из списка товаров. Но они выставляются только при нажатии на "Сбросить фильтры". Поправь это пожалуйста.

А в целом все сделано хорошо. Молодец!

2020-03-28 08:49 UTC, kuflash commented on src/context/filter.js
> +import { createContext } from "react";
Это ведь уже лишний файл? Забыл удалить?

2020-03-30 16:21 UTC, ensisf commented on src/context/filter.js
> +import { createContext } from "react";
> Из критичных моментов только момент с первоначальными значениями фильтра. Почему-то при открытии страницы, `min` и `max` значения цены выставлены в 0. Хотя в одном из предыдущих этапов было условие, что по умолчанию они должны быть равны `min` и `max` из списка товаров. Но они выставляются только при нажатии на "Сбросить фильтры". Поправь это пожалуйста.
> 
Да, видимо при рефакторинге что-то сломал, а перед пушеи не перепроверил, спасибо)

2020-03-30 16:37 UTC, kuflash commented
Да, теперь вопросов нет. Можешь вливать в  `master`

2020-03-30 16:38 UTC, merged